services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: kaydevops79/vprofile-db
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
    
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBIT_DEFULT_PASS=guest
    
  vproapp:
    build: 
      context: ./Docker-files/app
    image: kaydevops79/vprofile-app
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/var/local/tomcat/webapps

  vproweb:
    build: 
      context: ./Docker-files/web
    image: kaydevops79/vprofile-web
    container_name: vproweb
    ports:
      - "80:80"
    volumes:
      - vproappdata:/var/local/tomcat/webapps
    
volumes:
  vprodbdata: {}
  vproappdata: {}

  

